### PR TITLE
[Program Card Images] Add a new, publicly-accessible bucket to store program images.

### PR DESCRIPTION
**Pull request by caitlinshk**
This PR updates our terraform deploy scripts to create a new bucket called `"${var.app_prefix}-civiform-public-files-s3"` that will store the program images. This bucket allows any person to view the objects in any `program-summary-image/program-*` folder.

### Admin flow
1) Run `bin/setup`.
2) On the local deploy:
     1) Enable the PROGRAM_CARD_IMAGES flag.
     2) As an admin, create a program then open the "Edit program image" page.
     3) Upload an image and save it.
     4) Verify that the program card preview shows your new image.

### Applicant flow
Follow the steps above, then:
1) As an admin, publish the program with the image.
2) Logout.
3) Verify that as an applicant, the programs homepage shows the image you uploaded as an admin.

### Restricted bucket access via URL testing
1) Inside the AWS console for the dev site, upload an image that's **not** in a `program-summary-image/program-*` folder.
2) Copy the URL.
3) Paste that URL into a new tab in the browser.
4) Verify that you get an Access Denied error.
5) (If you copy the URL for an image that **is** in a `program-summary-image/program-*` folder, pasting that URL into a new tab should download the image.)

### Restricted bucket access via AWS CLI
I created an AWS account with my personal email and configured its credentials on a machine that does *not* have my CiviForm AWS credentials. I verified that I was able to download images from the bucket, but was prevented from listing objects in the bucket or uploading new images to it:

image

### Re-deploy
1) Run `bin/setup` without any of the changes in this PR.
2) As an admin, create some new programs.
2) (Note that as an admin, if you try and upload a program image, you should get a "NoSuchBucket" error.)
2) Run `bin/deploy` **with** the changes in this PR.
2) Verify that the re-deploy succeeds.
3) As an admin, verify that you can now upload program images.
4) As an applicant, verify that you can see program images.

### CODE REVIEW

**Comment by caitlinshk** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #279** <a href="https://app.graphite.dev/github/pr/civiform/cloud-deploy-infra/279?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/civiform/cloud-deploy-infra/279?utm_source=stack-comment).

**Review by bion — APPROVED** [review]
Please confirm that files cannot be listed or uploaded via API (CLI is a fine way to test this) from a public user

**Review by rockycodes — APPROVED** [review]
Looks good! Thanks for the helpful comments 👍

**Comment by caitlinshk** [comment]
@bion : I confirmed that I wasn't able to list or upload files via AWS CLI, updated the PR description with exactly how I verified that.

**Pull request merged**
